### ISSUE TITLE
Inaccurate Local Administrators in certain conditions

### ISSUE THREAD

**Issue by ngebhar2** [dafthack/HostRecon#2]
Hello,
If your domain has any groups that have "administrators" in the group name the members of that group will be listed as a local administrator to your machine.

I think this can be fixed by changing the line:
`$Admins = Get-WmiObject win32_groupuser | Where-Object { ($_.GroupComponent -match 'administrators')  } | ForEach-Object {[wmi]$_.PartComponent } | Select-Object Caption,SID | format-table -Wrap | Out-String`

to 

$Admins = Get-WmiObject win32_groupuser | Where-Object { ($_.GroupComponent -match 'administrators') -and ($_.GroupComponent -match "Domain="$env:COMPUTERNAME"") } | ForEach-Object {[wmi]$_.PartComponent } | Select-Object Caption,SID | format-table -Wrap | Out-String

(the double quotes around $env:COMPUTERNAME need to have the grave escape character in front of them, but alas that character is what GitHub uses to define their code snippets)

This includes ($_.GroupComponent -match "Domain=`"$env:COMPUTERNAME`"") to only pick local groups.

**Comment by dafthack** [comment]
Thanks for this! It's been updated.
