### ISSUE TITLE
Adding CrowdStrike EDR and Verdasys Digital Guardian DLP

### ISSUE THREAD

**Issue by jnqpblc** [dafthack/HostRecon#4]
Please add something like the following.

# Endpoint Detection and Response (EDR)
#C:\Program Files\CrowdStrike\CSFalconContainer.exe
#C:\Program Files\CrowdStrike\CSFalconService.exe
if ($ps.ProcessName -like "*CSFalcon*")
{
Write-Output ("Possible CrowdStrike Falcon EDR process " + $ps.ProcessName + " is running.")
} 

# Data Loss Prevention (DLP)
#C:\Program Files\DGAgent\dgagent.exe
#C:\Program Files\DGAgent\DgService.exe
#C:\Program Files\DGAgent\DgScan.exe
#C:\Program Files\DGAgent\verity\kv\_nti40\bin\kvoop.exe
if ($ps.ProcessName -like "*dgagent*") -or ($ps.ProcessName -like "*DgService*") -or ($ps.ProcessName -like "*DgScan*")
{
Write-Output ("Possible Verdasys Digital Guardian DLP process " + $ps.ProcessName + " is running.")
} 

# Generic Data Loss Prevention (DLP) Process used by several, including Webroot and DG
if ($ps.ProcessName -like "*kvoop*")
{
Write-Output ("Possible Unknown DLP process " + $ps.ProcessName + " is running.")
}

**Comment by dafthack** [comment]
Thanks! I just added these in.

**Comment by jnqpblc** [comment]
Also, looks like repmgr32.exe and repmgr64.exe present on systems with Carbon Black.

This is a list of all files scanned in HerdProtect that belong to Confer Technologies, Inc. (Carbon Black)
https://www.reasoncoresecurity.com/signer-confer-technologies-inc-3c1ec6a0ae6013040bb3efb4cce6fb69.aspx
